### ISSUE TITLE
recoverWith and switch

### ISSUE THREAD

**Issue by maxhoffmann** [cujojs/most#355] opened 2016-11-16 17:27 UTC
Hey there!

I’ve encountered a problem, where I’m not sure if it’s my code or a bug. I have created a helper function called `retry`, which takes a stream and returns the same stream altered, so that it automatically retries on errors with an exponential backoff.

This is the helper function:

### retry
```js
export function retry(createOriginalStream, { delay = 1000, exponentialDelay } = {}) {
  let currentDelay = exponentialDelay || delay;
  const $original = createOriginalStream().multicast();

  $original
    .take(1)
    .recoverWith(() => most.empty())
    .forEach(() => {
      currentDelay = delay;
    });

  return $original
    .recoverWith(error =>
      most.just()
        .delay(currentDelay)
        .map(() =>
          retry(createOriginalStream, { delay, exponentialDelay: currentDelay * 2 })
        )
        .switch()
    );
}
```

This is how it’s used:

### failure case
```js
most.combine((someValue, someBoolean) =>
  someBoolean
    ? retry(() => createStream(someValue))
    : most.empty()
  , someValueStream, someBooleanStream)
  .switch()
```

If `someBoolean` changes from `true` to `false` and the stream is failing, it keeps retrying although there shouldn’t be any listeners. Each time `someBoolean` switches another failing stream is added trying to recover.

I’m not sure if I’m doing something wrong or if `switch` fails to unsubscribe from the new recovered streams returned by `recoverWith`.

Any help is appreciated. :)

**Comment by maxhoffmann** [comment] 2016-11-16 18:03
Requirebin doesn’t let me create a link so here is a reproduction of the issue. (copy paste into [requirebin](http://requirebin.com/) still works)

```js
const most = require('most');

function retry(createOriginalStream, { delay = 1000, exponentialDelay } = {}) {
  let currentDelay = exponentialDelay || delay;
  const $original = createOriginalStream().multicast();

  $original
    .take(1)
    .recoverWith(() => most.empty())
    .forEach(() => {
      currentDelay = delay;
    });

  return $original
    .recoverWith(error => {
      console.log(error);
      return most.just()
        .delay(currentDelay)
        .map(() =>
          retry(createOriginalStream, { delay, exponentialDelay: currentDelay * 2 })
        )
        .switch()
  });
}

const clicks = most.fromEvent('click', window);

clicks
  .tap(console.log)
  .map(() =>
    retry(() => most.throwError('fails'))
  )
  .switch()
  .forEach(console.log);
```

I expect that for every click one new failing stream is created and the error is logged with an exponential delay.

What happens is that new clicks add new streams retrying without unsubscribing from the old ones, so that 'fail' gets logged multiple times whenever any of the started streams try to recover.

**Comment by briancavalier** [comment] 2016-11-16 22:34
Hey @maxhoffmann, thanks for all the example code.  A few of things catch my eye initially ... not sure if they are causing a problem, but figured I'd mention to see if they help us understand what's going on.

`retry` observes `$original` and also returns a stream derived from `$original`.  Hidden observations like this make me suspicious :)  In general, `retry` itself can't know the relationship between the timing of when it observes `$original` and when the someone else does.  That makes the timing/interleaving of any side effects between the two observations unclear.  For example, I'm finding it difficult to understand the (implicit) timing of when `currentDelay` is overwritten in the first observation vs when it is used in the second.

All of that makes me wonder if there's a solution that doesn't require `retry` itself to observe the stream.  You wrote this great spec for what `retry` should do:

> retry, which takes a stream and returns the same stream altered, so that it automatically retries on errors with an exponential backoff

:+1: Maybe we can work from that to a simpler solution.  I'll try out your example an requirebin and stare at this a bit more and hopefully post a few more thoughts.

**Comment by maxhoffmann** [comment] 2016-11-17 10:17
Hey @briancavalier! Thanks for the quick response!

I suspected subscribing to `$original` twice might be an issue, but even without resetting the delay on a successful event, the behaviour is still the same.

```js
const most = require('most');

function retry(createOriginalStream, { delay = 1000, exponentialDelay } = {}) {
  let currentDelay = exponentialDelay || delay;
  
  return createOriginalStream
    .recoverWith(error => {
      console.log(error);
      return most.just()
        .delay(currentDelay)
        .map(() =>
          retry(createOriginalStream, { delay, exponentialDelay: currentDelay * 2 })
        )
        .switch()
  });
}

const clicks = most.fromEvent('click', window);

clicks
  .tap(console.log)
  .map(() =>
    retry(most.throwError('fails'))
  )
  .switch()
  .forEach(console.log);
```

Clicking multiple times logs `fail` multiple times as well. It should log it just once and then again after the delay and so on.

**Comment by briancavalier** [comment] 2016-11-17 13:29
Thanks for simplifying it!  I think that will be the key to understanding what is going on: trying to find the simplest reproducible case.  I'll try a bit of that today as well.  The simpler version is still messing with my brain a bit :)  Those nested switches are tough to reason about.  I wonder what would happen if you use `join` instead of `switch`.  I'll try that as well--maybe it will shed some light.

Here's a [very simple retry with exponential backoff function](https://esnextb.in/?gist=b923d3944931266d7d850d35c26ede8a).  It's slightly different from yours in that it takes a stream instead of a stream-creating function.  Maybe you can use it directly so you aren't blocked on your project.

**Comment by maxhoffmann** [comment] 2016-11-17 13:58
Yeah, I’ve had `flatMap` at first and switched to `switch` hoping, that it fixes the issue. I agree it’s quite complicated. I’ve tried multiple versions and each of them didn’t quite work.

Thanks for creating an exponential backoff function! I will give it a try.

My specific use case is wrapping XHR requests and EventSource streams, in case the server does not respond. To be very precise `retry` should convert a stream into one that tries to recover exponentially whenever an error is encountered. This may happen at the beginning or after some time. If there is an error the retry cycle starts with a delay that increases exponentially. After a successful event is received the delay should reset (so that it doesn’t wait a minute if another error occurs).

**Comment by briancavalier** [comment] 2016-11-17 14:02
> After a successful event is received the delay should reset (so that it doesn’t wait a minute or longer if another error occurs)

Ah, right, makes sense.  Mine def doesn't do that, but I can see why it's important :)  I'll see if I can tweak it to make it reset on each success.

**Comment by briancavalier** [comment] 2016-12-05 00:43
Hey @maxhoffmann, sorry for taking a bit to get back to this, but I think I've got a working [retry-with-backoff that resets after seeing at least one successful event](https://esnextb.in/?gist=3a55407c2aa8db6cce76abb983457d28).  I haven't tested it much beyond the simple manual test in the esnextbin, but I think it's at least fairly close.

It's relatively simple, and just expands on the idea in the previous (non-reset) one by tracking whether at least one successful event has been seen, and tracking 2 delays instead of just one.  No multicast needed so far.  I'd love to find a way to avoid having to use a captured `ok` mutable variable, but I haven't found a good way yet.

Anyway, let me know if this is close to what you need.

**Comment by maxhoffmann** [comment] 2016-12-05 11:46
Thanks a lot @briancavalier for working on this!

Can you explain how the second argument to `recoverWith` is handled? It doesn’t seem to be documented.

I will replace my `retry` function in our app with yours and let you know if it fixes the issue.

Cheers again! 🙏

**Comment by briancavalier** [comment] 2016-12-05 16:42
@maxhoffmann Hope it works for you!  I didn't use a `createOriginalStream` function (I just passed in a stream instead), but I think it can be converted to using a function fairly easily.

As for `recoverWith`, I used the [function form of `recoverWith`](https://github.com/cujojs/most/blob/master/docs/api.md#mostrecoverwithf-stream---stream) rather than the fluent version.  The function version takes 2 params, the first is the function (same as the fluent version) and the second is the stream.  E.g. these are equivalent:

```js
s.recoverWith(f)
recoverWith(f, s)
```

It's just personal preference ... no functional difference.

**Comment by maxhoffmann** [comment] 2016-12-05 16:49
Ah, right. Totally missed that. Yeah I’m used to the dot notation and just got confused. I’ve used a function like `createOriginalStream`, because I thought it might solve the problem I had, so that wasn’t really a requirement. :)

**Comment by briancavalier** [comment] 2017-01-03 13:36
Hi @maxhoffmann.  Just wondering if the most recent retry w/reset+backoff has worked out for you.

**Comment by maxhoffmann** [comment] 2017-01-18 18:18
Hey @briancavalier! Sorry for the late response. Unfortunately it did not fix my problem. I haven't been working in this specific issue for a while, but I'll let you know if I do again.

**Comment by Sinewyk** [comment] 2017-02-07 13:57
Not sure this helps, but I asked about a retry function a "long" time ago, and this is what it looks like

`const retry = (n, stream) => stream.recoverWith(e => n === 0 ? most.throwError(e) : retry(n - 1, stream));`

I had to dig it up the gitter history, now I saved it as a gist for a quick lookup.

Seems to do the job.

**Comment by briancavalier** [comment] 2017-08-13 01:25
@maxhoffmann Closing this, but please reopen if you need.

@Sinewyk Thanks for posting that retry.  I [added it to the Recipes wiki](https://github.com/cujojs/most/wiki/Retry).

**Closed by briancavalier** 2017-08-13 01:25 UTC
