### ISSUE TITLE
The mapping function passed to `map` is invoked once for every observer for one event on base stream

### ISSUE THREAD

**Issue by maciasello** [cujojs/most#139] opened 2015-05-31 20:14 UTC
The simplest reproducing scenario:
```js
var orig;
orig = most.of(7).map(function() {
  console.log("expensive operation");
  return 5;
});
orig.observe(function(e) {
  console.log("obs 1", e);
});
orig.observe(function(e) {
  console.log("obs 2", e);
});
```

My usage is that for every user event (think "click") there is an expensive operation performed (e.g. AJAX call for to-do list) then multiple derivative streams carrying the result processed in different ways (e.g. a stream with to-do list content and a stream with to-do list length) are created. Each of the derivative streams is observed by one observer, but still the expensive operation is invoked many times - once for each observer even though there was one "click" only.

A bit more complex scenario (to ilustrate the derivative streams) - it bahaves the same if `.fromEvent(...)` is changed to `.of(...)`:
```js
var derivative1, derivative2, orig;

orig = most.fromEvent("click", someDiv).map(function(e) {
  console.log("expensive operation");
  return 7;
});

derivative1 = orig.map(function(e) {
  console.log("sub-op 1");
  return e + 1;
});

derivative1.observe(function(e) {
  console.log("observer 1", e);
});

derivative2 = orig.map(function(e) {
  console.log("sub-op 2");
  return e - 1;
});

derivative2.observe(function(e) {
  console.log("observer 2", e);
});
```
Console output on the latter:
```
expensive operation
sub-op 1
observer 1 8
expensive operation
sub-op 2
observer 2 6
```

Is this expected or a bug? While I can [partially] visualize to myself the multiple sinks pulling the events from sources and thus causing multiple invocations of a mapper it is against my gut feeling that one source event should be mapped once and then fed to different consumers. Is this reasoning correct?

**Comment by briancavalier** [comment] 2015-06-02 01:07
Hey @maciasello!  I'll call this known, but in search of the best solution.  Because most pre-1.0 has been heavily focused on performance, it optimizes for the single-subscriber case by not bothering to maintain subscriber lists at each node.  Multicast subscriptions can be added easily [via composition](https://github.com/cujojs/most/blob/master/lib/source/MulticastSource.js).  However, we haven't exposed an API for it yet.

One issue is that there's no way for each combinator to know if the stream it returns will end up having multiple observers.  I think there are 2 possible solutions to consider for 1.0:

1. Automatically make every combinator return a multicast stream.  This would be super-convenient for callers, but would introduce lots of unnecessary overhead since only a very small number of streams would ever actually end up needing to be multicast.
2. Provide a simple API for the caller to declare that a stream should be multicast.  For example, if a function composes a stream, it could return a multicast version of the stream by doing something like: `return stream.multicast();`.  The upside is that it minimizes amount of multicasting, and the downside is that you might forget.

Any thoughts?

**Comment by maciasello** [comment] 2015-06-09 19:54
@briancavalier, It seems the tradeoffs are on both sides and I agree that performance in `most` is a must. As for 1. maybe there is a way for sources to upgrade to MulticastSources when the second subscriber appears? 2. will be useful. At least for now. The main problem is that I WILL forget :) What is more it seems to be the first combinator that exposes internal machinery instead of functionality. While I'm ok with that don't you feel that it doesn't belong to the API? IMHO it should be some magic inside `most` to handle that properly and efficiently (no pressure here :D just my gut feeling that if I knew how I would push in that direction :))

**Comment by briancavalier** [comment] 2015-06-10 01:28
> don't you feel that it doesn't belong to the API?

I completely agree.  I would like for it to just work, and while that's possible, it's not without tradeoffs.  The problem is really inherent in a push-based propagation system:  to allow sharing, it has to maintain subscriber lists at any node that *might* be shared.

> it should be some magic inside most to handle that properly and efficiently

I think it can be done relatively efficiently, but it will never be as efficient (in terms of event propagation speed) as what is there now.  Most currently has so much headroom right now, it may well be worth the hit.

> if I knew how I would push in that direction

Haha, subtle :)  I have some ideas I'm planning to try soon.  Hopefully sometime this week I'll push a branch.

**Comment by xgrommx** [comment] 2015-06-10 08:35
Looks like that a method ```multicast``` is undocumented.

**Comment by maciasello** [comment] 2015-06-10 14:46
@xgrommx, I would say more: it does not exist (yet?) :)

@briancavalier,
>> if I knew how I would push in that direction

> Haha, subtle :) I have some ideas I'm planning to try soon. Hopefully sometime this week I'll push a branch.

Heh, it worked well :) but I meant I would try to do it by myself (if I knew how).

**Comment by briancavalier** [comment] 2015-06-10 18:13
@xgrommx See #143 where we're discussing adding it into the public API.

**Comment by xgrommx** [comment] 2015-06-11 05:54
@briancavalier As I understood that is similar as in Rx?

**Comment by briancavalier** [comment] 2015-06-12 00:19
@xgrommx Yeah, it'd be very similar to [RxJS's share](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/share.md)

**Comment by briancavalier** [comment] 2016-03-25 12:30
Closing, since `multicast` has been added and released.

**Closed by briancavalier** 2016-03-25 12:30 UTC
