### ISSUE TITLE
Merged Streams Error

### ISSUE THREAD

**Issue by jordalgo** [cujojs/most#213] opened 2016-03-18 13:03 UTC
@briancavalier - At the moment, a stream created by merging two streams ends if one of the streams throws an error, even if you have a catch for it. E.g.:
```
var mergedStream = stream1.merge(stream2);
mergedStream
.forEach(fn)
.catch(console.log.bind(console));
```
I kinda feel like you should still be able to observe and get events from this merged stream if you have a catch for the error instead of having to do something like:
```
var mergedStream = most.create(function(add, end, error) {
  stream1
    .forEach(add)
    .catch(console.log.bind(console));
  stream2
    .forEach(add)
    .catch(console.log.bind(console));
});
```
But was curious what you thought.

**Comment by briancavalier** [comment] 2016-03-19 03:07
Hey @jordalgo.  This is a great question, and there's a good bit wrapped in it.  I'll see if I can unpack it and explain.  Please bear with me as this got a little long, and there may be things here you already know!

First, I feel like I should provide a bit of context on errors and error handling in most.js.  The *meaning* of an error in a most.js event stream is that the event stream has entered a state where it cannot possibly produce any more events for some exceptional reason.  IOW, it has failed utterly and unrecoverably.  

This is part of the semantic contract of event streams in most.js.  It's very important that *all* event streams obey this contract.  If some code returns a stream to you, it shouldn't matter how the stream was created/transformed/filtered/merged etc before you get your hands on it.  You should be able to interact with it without having to know *how* it was created.

To that end, a merged stream is ... just another stream, and so it adheres to the same error contract as any other stream.  Merge's contract is that when any of the "input" streams (those that were merged) errors, the merged stream errors.

It would certainly be possible to create some new type of merged stream that has different error characteristics.  For example, a new stream that errors only if all of its "input" streams error.  However, you'd need to think carefully about it, since not surfacing those errors could create a debugging headache for someone.

Ok, back to your example.

The catch you are using is at the very "right end" of the stream.  Once the error reaches that point, it has propagated through the entire stream *and* the promise representing the final state.  Since promises are "write once" future values, they are a good fit for representing the one time conclusion of a stream, be it a successful ending or an error.  In this case, once the error reaches the promise, the error is final.  The catch cannot "reach back" and prevent the stream from erroring.

Instead, because most.js is declarative, you'd  arrange declaratively, *up front*, what you want the behavior of a stream graph to be, like a blueprint for a machine.  Then, like pressing a big "Go" button, you start the machine by calling reduce/drain/observe/forEach.

So, one way you might create a merged stream that allows events to continue when any of it's input streams errors is to use `recoverWith` to arrange to send the errors "somewhere else", and simply not propagate it through the stream.  I'll use `console.log` as the "somewhere else", but you could just as easily parameterize it.  For example:

```js
import { merge, empty } from 'most'

const handleError = e => {
  console.log(e)
  return empty()
}

// merged will continue to propagate events even if
// stream1 or stream2 errors.  It will end if *both* stream1
// and stream2 error
const merged = merge(
  stream1.recoverWith(handleError),
  stream2.recoverWith(handleError)
)

merged.forEach(x => console.log(x))
```

That's just one possible behavior, of course.  It could be a starting point for a custom operator, for example.  You'd still need to decide what you want to do with the errors, but this is a nice, declarative start. 

I hope that helps to explain the meaning of errors, why the error handling contract is important, and how you might construct your own custom behavior if you need.  That's certainly one goal of most.js: make it possible for people to build custom operators easily from existing ones.

Please feel free to continue to discuss!

**Comment by jordalgo** [comment] 2016-03-21 01:00
@briancavalier Thanks so much for the very detailed explanation! I definitely see the logic about a merged stream being just another stream and should therefore end when an error is thrown. 

I've been tinkering a bit with error bubbling for observables/streams -- contemplating just going with an Either Monad from [Sanctuary](https://github.com/plaid/sanctuary) as opposed to calling the 'error' method within the stream. 

But I was also thinking it might be nice for the stream to keep track of it's own status so you could do something like this: 

```javascript
var mergedStream = stream1.merge(stream2);

function recoverMerged(s1, s2, e) {
  if (s1.isComplete) { // or 'hasError' perhaps
    return s2;
  } else {
   return s1;
  }
}

mergedStream
  .recoverWith(recoverMerged.bind(null, stream1, stream2))
  .forEach(console.log.bind(console));
```
(And maybe even cooler if a merged stream had a record of the stream that created it).

In general I think it would be good if you could query a stream for it's status so you don't have to explicitly call catch on a possibly errored stream; though perhaps there is something inherently problematic with internally keeping track of state, which makes it a bit less functional perhaps.

**Comment by jordalgo** [comment] 2016-03-21 12:45
I also noticed something interesting that might just be a bug but if a stream publisher calls its error fn, then another function observes this errored stream it will restart e.g.

```javascript
var stream1 = most.create(function(add, end, error) {
  var count = 0;
  setInterval(function() {
    add(count++);
  }, 1000);
  setTimeout(function() {
    error('error timeout');
  }, 5000);
});

stream1.forEach(console.log.bind(console));

setTimeout(function() {
  stream1.forEach(function(a) {
    console.log('restarted', a);
  });
}, 6000);
```
Produces this output:
```
0
1
2
3
restarted 0
restarted 1
restarted 2
restarted 3
```

**Comment by briancavalier** [comment] 2016-03-21 13:24
I should have time to answer the question about statefulness later today, but quickly about "restarting":

> I also noticed something interesting

This is correct behavior.  Check out the [docs for most.create](https://github.com/cujojs/most/blob/master/docs/api.md#mostcreate), specifically this paragraph:

> Note that the publisher will not be called until there is demand for the stream's events. Specifically, the publisher will be called when the number of observers goes from zero to one. Likewise, the dispose function will be called when the number of observers again returns to zero. The publisher would then be called again if the number of observers subsequently goes from zero to one, and so on.

most.create is, in many ways, an escape hatch.  It is the thing you reach for when you are forced into a situation where no declarative solution will work.  By using it, you effectively opt into managing lots of things yourself, such as timing and race conditions, and how the stream should behave in a situation like your example.

**Comment by jordalgo** [comment] 2016-03-21 22:26
@briancavalier No worries on the promptness of the responses. I'm in no rush :+1: 

And perhaps what I'm about to say should be addressed in a separate issue (or gitter channel) as I seemed to have diverged a bit from the first thing I asked, which you have already answered. But, as long as you're still reading, I suppose I'm having an issue with observables in general (or at least the way most.js and RxJs implement them). Perhaps there isn't a use case that would really highlight this but I find it troubling that an event stream is entirely dependent on what is subscribed to it. In the way that a stream can be re-started after it's errored, or in the case of RxJS, restarted if observed by a different function. To me (and maybe I'm alone here) an event stream is something that is happening regardless of if something is listening/subscribed to it. (I'm stealing someone's words) A tree _can_ fall in a forest even if no one is around to hear it :smile: 

Perhaps someone might say that's the difference between observables and streams even though I still don't have a clear understanding of their differences.

**Comment by briancavalier** [comment] 2016-03-22 02:03
> an event stream is entirely dependent on what is subscribed to it

I'll be completely honest: It's not just you, and, imho, the current situation is actually a bit worse than that.  The current generation of popular push-based event stream implementations (which includes most.js and RxJS) conflate (at least) two concepts.  I'll call them data and true events, where true events have an integral notion of occurrence time that is at least as important as the data carried by the event.

Data streams act more like arrays: their "events" aren't really events at all and are available to any new observer.  Some folks call these kinds of streams "cold".

Event streams are "tree falls in a forest".  I usually say they are like radio: the music is being broadcast even when you aren't tuned in, and tuning in to a station doesn't mean hearing all music from the beginning of that station's existence.  Some folks call these kinds of streams "hot".

Having to think about this distinction creates additional cognitive load, as you've observed (heh).

Most.js was created before I had a full appreciation for all of this.

Figuring out how to deal with the situation is tricky.  There are approaches where the hot/cold distinction simply doesn't exist.  For example, approaches based on *real* FRP using persistent data structures or Arrows, such as [netwire in Haskell](https://wiki.haskell.org/Netwire).  I created a [prototype of one such approach](https://github.com/briancavalier/catalyst), based on Conal Elliot's push-pull FRP.  It's very different from most.js in many ways, and rules out several problems by design.  For instance, there is no notion of hot/cold, and it is fully referentially transparent.

Of course, it has a few issues of it's own.  I don't believe such an approach could ever have the performance characteristics of most.js (at least not in JavaScript). That may simply *not matter*, and it might be [plenty efficient for real front-end applications](https://cdn.rawgit.com/briancavalier/catalyst/master/examples/bounce/index.html).  The reduced cognitive load could be well worth it.

Another solution would be to simply declare that most.js will only support events, aka "hot" streams, and do away with the notion of streams where time doesn't matter, like those created from arrays.  Or, vice versa, deal only with data streams.

If you're interested in talking more about this, please do join us in [the gitter chat](https://gitter.im/cujojs/most)!

**Comment by briancavalier** [comment] 2016-03-22 02:19
> contemplating just going with an Either Monad from Sanctuary as opposed to calling the 'error' method within the stream.

Seems like a perfectly reasonable thing to do :)  If you try it, and can share, I'd be interested to see.

> the stream to keep track of it's own status

While most.js uses mutable object properties internally for performance reasons, it tries not to expose those to callers.  It allows stateful computations via combinators like scan and loop, but in terms of stream objects themselves, they are immutable.

I'd prefer to try to promote declarative approaches whenever possible.  Introducing a mutable property or way to query some (invisible) mutable state might tempt folks to think imperatively.  Also, given the current hot/cold situation, I don't think it'd be possible for a stream to have a singular property representing whether it had errored or not: it'd have to be a property of the relationship between a stream and an observer.

I'll close this issue, since we worked through the original merge issue, but please do feel free to continue to discuss here!

**Closed by briancavalier** 2016-03-22 02:19 UTC

**Comment by jordalgo** [comment] 2016-03-22 14:30
@briancavalier Or right! I forgot about hot vs. cold observables. Again, I really appreciate you taking the time to explain the history behind some of these things. I'll do a bit more thinking on it as well, check out those links you posted, and get some good gitter convos going. 

Also wanted to share this stream lib I found a while back that I thought worked pretty well but maybe, as you said, doesn't have have the same level of performance: [Flyd](https://github.com/paldepind/flyd)

**Comment by briancavalier** [comment] 2016-03-23 19:07
Yes, flyd is a nice library.  I have a lot of respect for @paldepind's work.
