### ISSUE TITLE
concatMap with deferreds / chaining promises

### ISSUE THREAD

**Issue by aaronshaf** [cujojs/most#103] opened 2015-03-11 01:29 UTC
Any ideas on how I would do the equivalent of this in most?

http://jsbin.com/kodoni/2/edit?js,console

```javascript
var source = Rx.Observable.of(1,2,3,4)
  .concatMap(function(x) {
    return Rx.Observable.defer(function() {
      return new Promise(function(resolve, reject) {
        setTimeout(function() {
          resolve(x);
        }, 1000);
      });
    });
  })
  .subscribe(function(i) {
    console.log(i);
  });
```

**Comment by briancavalier** [comment] 2015-03-11 01:38
Hmmm, looks kind of complex for what it seems to do when I run it. Is the intention to print a counter that increments at 1 second intervals?

**Comment by aaronshaf** [comment] 2015-03-11 01:42
Given a stream, I would like to run async operations on each value, but only one at a time. Similar to async's `.series`

Scenario: a stream of urls that need to be downloaded one at a time.

**Comment by aaronshaf** [comment] 2015-03-11 01:44
Ideally concatMap would process a series of promises in sequence:

```javascript
most.from([url1, url2, url3])
  .concatMap(function(url) {
    return doSomethingAsyncWith(url) // return a promise
  })
  .then(console.log.bind(console))
```

**Comment by davidchase** [comment] 2015-03-11 03:21
Aren't you simply missing the consumer part? such as `forEach` 
```js
most.from([url1, url2, url3])
  .concatMap(function(url) {
    return most.fromPromise(doSomethingAsyncWith(url))
  })
  .forEach(console.log.bind(console))  //-> url1.data, url2.data, url3.data in that order 
  .then(function(){
     console.log('done');
  })
```
the `forEach` returns a promise which we can use signal that all of the promises have been resolved.

**Comment by aaronshaf** [comment] 2015-03-11 03:25
While that outputs the resolved values in sequence, that doesn't execute the promises themselves in sequence.

**Comment by briancavalier** [comment] 2015-03-11 11:28
Ah, cool, thanks for clarifying.  Here are two ways that came to mind.  The first is more declarative, and the second a bit more imperative.  In my mind, the first represents the goal more clearly: to accumulate a sequence of urls into a sequence of future values concatenated in time.  The `skip(1)` is slightly unfortunate.

```js
most.from([url1, url2, url3])
	.scan((queue, url) => queue.then(() =>  doSomethingAsyncWithUrl(url)),
		Promise.resolve())
	.skip(1)
	.await()
	.observe(content => console.log(content));

most.from([url1, url2, url3])
	.concatMap(url => {
		return most.create((add, end) => {
			add(doSomethingAsyncWithUrl(url));
			end();
		})
		.await();
	})
	.observe(content => console.log(content));
```

By design, RxJS considers promises to be another kind of observable.  In contrast, most.js keeps Promise and Stream separate by design, so operations don't implicitly turn promises into event streams.  The reason is that we feel this gives you more control, by using `await()` for example, over when promises' ultimate value gets merged into a stream.

**Comment by briancavalier** [comment] 2015-03-11 11:39
Or by `unfold`ing:

```js
most.unfold(function(urls) {
	return urls.length === 0
		? { done: true }
		: fetch(urls[0]).then(content => { value: content, seed: urls.slice(1) })
}, [url1, url2, url3])
	.observe(console.log);
```

**Comment by briancavalier** [comment] 2015-03-15 19:05
@aaronshaf Did the examples above help?

**Comment by aaronshaf** [comment] 2015-03-16 02:54
I haven't tried the latest yet. I will and report back. I am trying to prevent the premature creation of promises.

**Comment by aaronshaf** [comment] 2015-03-16 19:17
I am having a tough time getting this to work in a browser (bundled with webpack):

https://gist.github.com/aaronshaf/6b20f1e4c0bd3d78b704

Chrome complains about an "Illegal invocation."

Works fine when run directly with `babel-node`

**Comment by briancavalier** [comment] 2015-03-16 20:44
@aaronshaf Sorry, my bad.  You can't call `console.log` as a function in most envs.  It works in node/io.js, but not in many browsers.  [Here's a fork of the gist](https://gist.github.com/briancavalier/36d77d029e395b09686a)

**Comment by aaronshaf** [comment] 2015-03-16 23:56
Ah! A simple fix!

This works _wonderfully_, and it is exactly the kind of thing I was looking for. Thank you!

**Closed** 2015-03-16 23:56 UTC

**Comment by briancavalier** [comment] 2015-03-17 01:07
Yay! :+1:

**Comment by rektide** [comment] 2016-10-06 18:24
Hey all, I had a similar but slightly different issue that this ticket helped me through- rather than trying to run fetch() multiple times on a list of urls, I was getting a stream of domainNames, and had a function that returned a promise with a list of records in the name. I was trying to figure out how to flatly take the Array-fulfilling promise results to a new stream.

I used @briancavalier's suggestion of [unfolding](https://github.com/cujojs/most/issues/103#issuecomment-78247645) to get by this, in slightly different form. It took me a pass or three to make right/not-ugly, so I built a library for the final version- [most-promise-spread](https://github.com/rektide/most-promise-spread).

From [the example](https://github.com/rektide/most-promise-spread/blob/master/example/spread.js#L8) there, I got `mostPromiseSpread(Promise.resolve([.forEach(x => console.log(x*2))`. For domainNames/records, it looks something like:
`domainNames.concatMap(n => mostPromiseSpread(lookupRecords(n))`.
